<!DOCTYPE html>
<html>
<head>
    <title>Stock Report</title>
    <link rel="stylesheet" href="{{ asset('css/app.css') }}">
    <style>
        body {
            font-family: sans-serif;
        }
        table {
            width: 100%;
            border-collapse: collapse;
            font-size: 14px;
        }
        table, th, td {
            border: 2px solid black;  /* 2px thick black borders */
            padding: 6px;
            text-align: center;
        }
        th {
            background-color: #f3f3f3;
        }
        h2 {
            font-size: 10mm;
            font-weight: bold;
            text-align: center;
            margin-bottom: 20px;
        }
        tfoot {
            background-color: #f9f9f9;
            font-weight: bold;
        }
        @media print {
            .no-print {
                display: none;
            }
        }
    </style>
</head>
<body class="p-4">

    <div class="no-print" style="margin-bottom: 10px;">
        <button style="background-color: #28a745; color: white; border: none; padding: 10px 15px; border-radius: 5px; cursor: pointer;" onclick="window.print()">Print</button>
    </div>

    <h2>Stock Report</h2>

    <div style="margin-bottom: 15px; font-size: 14px;">
        <p style="text-align: right; font-size: 12px; margin-bottom: 10px;">
            Report generated by: <strong>{{ $userName }}</strong> on {{ \Carbon\Carbon::now()->format('d-m-Y H:i') }}
        </p>
        <ul style="list-style-type:none; padding-left: 0; margin-top: 5px;">
            <li><strong>From Date:</strong> {{ $fromDate ? \Carbon\Carbon::parse($fromDate)->format('d-m-Y') : 'All' }}</li>
            <li><strong>To Date:</strong> {{ $toDate ? \Carbon\Carbon::parse($toDate)->format('d-m-Y') : 'All' }}</li>
            <li><strong>Filter Type:</strong> 
                @if($filterType === 'purchase') Purchase Only
                @elseif($filterType === 'sale') Sale Only
                @else All Transactions
                @endif
            </li>
            <li><strong>Exclude Zero Purchased Products:</strong> {{ $excludeZeroPurchase ? 'Yes' : 'No' }}</li>
            <li><strong>Exclude Zero Stock In Hand:</strong> {{ $excludeZeroStock ? 'Yes' : 'No' }}</li>
        </ul>
    </div>
    <table>
        <thead>
            <tr>
                <th rowspan="2" style="vertical-align: middle; text-align: center;">S.No.</th>
                <th rowspan="2" style="vertical-align: middle; text-align: center;">Product Name</th>
                <th colspan="2">Total Purchased</th>
                <th colspan="2">Total Sold</th>
                <th colspan="2">Stock In Hand</th>
                {{-- <th rowspan="2" style="vertical-align: middle; text-align: center;">Last Purchase Date</th>
                <th rowspan="2" style="vertical-align: middle; text-align: center;">Last Sale Date</th> --}}
            </tr>
            <tr>
                <th>Quantity</th>
                <th>Value (Rs.)</th>
                <th>Quantity</th>
                <th>Value (Rs.)</th>
                <th>Quantity</th>
                <th>Value (Rs.)</th>
            </tr>
        </thead>
        <tbody>
            @forelse($stockData as $index => $item)
                <tr>
                    <td>{{ $index + 1 }}</td>
                    <td>{{ $item['name'] }}</td>

                    <td>{{ $item['total_purchased'] }}</td>
                    <td>{{ number_format($item['total_purchase_value'], 2) }}</td>

                    <td>{{ $item['total_sold'] }}</td>
                    <td>{{ number_format($item['total_sale_value'], 2) }}</td>

                    <td>{{ $item['stock_in_hand'] }}</td>
                    <td>{{ number_format($item['stock_value'], 2) }}</td>

                    {{-- <td>{{ $item['last_purchase'] ? \Carbon\Carbon::parse($item['last_purchase'])->format('d-m-Y') : '-' }}</td>
                    <td>{{ $item['last_sale'] ? \Carbon\Carbon::parse($item['last_sale'])->format('d-m-Y') : '-' }}</td> --}}
                </tr>
            @empty
                <tr>
                    <td colspan="10" style="text-align:center;">No data available</td>
                </tr>
            @endforelse
            <tfoot>
                <tr>
                    <td colspan="2" class="text-center">Totals:</td>
                    <td>{{ $totalPurchaseQty }}</td>
                    <td>{{ number_format($totalPurchaseVal, 2) }}</td>
                    <td>{{ $totalSoldQty }}</td>
                    <td>{{ number_format($totalSoldVal, 2) }}</td>
                    <td>{{ $totalStockQty }}</td>
                    <td>{{ number_format($totalStockVal, 2) }}</td>
                    {{-- <td colspan="2"></td> --}}
                </tr>
            </tfoot>
        </tbody>
    </table>

</body>
</html>
